### ISSUE TITLE
deleted when adding and added when deleting?

### ISSUE THREAD

**Issue by wayne-o** [flitbit/diff#38] opened 2015-03-05 08:19 UTC
If I add an item to an array and diff I get this:

![screen shot 2015-03-05 at 08 17 46](https://cloud.githubusercontent.com/assets/178060/6501423/4e492340-c310-11e4-840d-b0f79f8ad3f5.png)

Notice the DiffDeleted

if I remove that item and diff again I get:

![screen shot 2015-03-05 at 08 18 31](https://cloud.githubusercontent.com/assets/178060/6501427/5b3f50e2-c310-11e4-9d0c-a6d330c2bd71.png)

Is this expected behaviour?

**Comment by flitbit** [comment] 2015-03-06 18:44
Well no, that seems backwards to me. Are you adding the item to the end of the array and then removing it from the end?

**Comment by flitbit** [comment] 2017-04-25 00:22
I know it has been a long time, but I'm trying to clear some issues and haven't been able to duplicate. Can you post some code that illustrates the issue? In particular, I'd need to see what the arguments are in your call to `diff`.

**Comment by cerebralkungfu** [comment] 2024-02-01 22:02
Duplicate of #37, as far as I can tell. Closing. Fixed in v2.x

**Closed by cerebralkungfu** 2024-02-01 22:02 UTC
Labels: duplicate
